apiVersion: v1
kind: Service
metadata:
  name: togglemaster-service
  namespace: togglemaster
spec:
  type: NodePort
  selector:
    app: togglemaster
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000