apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
          # emptyDir Volume
          # volumes:
          #   - name: nginx-html
          #     emptyDir: {}
      #HostPath Volume         
      #volumes:
      #  - name: nginx-html
      #    hostPath:
      #      path: /data
      #      type: DirectoryOrCreate
      volumes:
        - name: nginx-html
          persistentVolumeClaim:
            claimName: nginx-pvc